name: ai_closet
description: A smart AI-powered digital closet with outfit suggestions, Pinterest integration, and more.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.16.0

  # Pinterest + HTTP + Auth
  http: ^1.2.1
  flutter_web_auth: ^0.5.0  # if you plan to handle OAuth manually

  # Image + AI
  image_picker: ^1.0.7
  tflite: ^1.1.2

  # Weather
  geolocator: ^11.0.0

  # Notifications
  flutter_local_notifications: ^16.3.0

  # Parsing
  xml: ^6.5.0
  json_annotation: ^4.8.1

  # Utility
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

fonts:
  - family: Orbitron
    fonts:
      - asset: assets/fonts/Orbitron-Regular.ttf

flutter:
  uses-material-design: true

  #assets: